services:
  - type: web
    name: hexacrimson-labs
    runtime: node
    rootDir: .
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://hexacrimson-labs.onrender.com
